Chore: Migrate edxapp docker build
ibm-skills-network/configuration pull request #3
Opened 2020-11-13 15:58 UTC by michaelroudnitski

This will probably be the largest one.

I excluded the **removal** of [ansible_overrides.yml](https://github.com/ibm-skills-network/configuration/blob/open-release/juniper.master/docker/build/edxapp/ansible_overrides.yml). We can remove it if necessary but I wasn't sure if we needed to. The Juniper ansible_overrides contains some vars that weren't present in our ironwood fork.

2020-11-14 00:32 UTC, michaelroudnitski commented on docker/build/edxapp/docker-run.sh
> +        edxapp-run.yml \
(also line 79)

may need to be changed to `edxapp.yml` for the reason described here https://github.com/ibm-skills-network/configuration/pull/7#issue-520890012

2020-11-16 23:35 UTC, danielrudn requested changes

2020-11-16 23:35 UTC, danielrudn commented on docker/build/edxapp/vars/build.yml
> +edx_platform_version: open-release/ironwood.master
The repo should point to github.com/edx/edx-platform, which should be the default.

The version should point to `open-release/juniper.master`

2020-11-17 15:50 UTC, michaelroudnitski commented on docker/build/edxapp/vars/build.yml
> +edx_platform_version: open-release/ironwood.master
Should we also change lines 25, 36 & 42?

2020-11-19 22:21 UTC, danielrudn commented on docker/build/edxapp/vars/build.yml
> +edx_platform_version: open-release/ironwood.master
No, those should still point to GHE

2020-11-19 22:21 UTC, merged