feat: mailchimp newsletter integration
ibm-skills-network/configuration pull request #76
Opened 2021-05-26 14:53 UTC by jamestang12

created a new command in docker-run.sh for mailchimp_sync_announcement

2021-05-26 19:53 UTC, ExiaSR requested changes

2021-05-26 19:53 UTC, ExiaSR commented on docker/build/edxapp/docker-run.sh
> +      eval "${edxpython} ${manage} ${service} --settings=bdu mailchimp_sync_announcement --langs ${BDU_PORTAL_MAILCHIMP_USER_LIST_ID} ${BDU_PORTAL_MAILCHIMP_API_KEY}"
```suggestion
      eval "${edxpython} ${manage} ${service} --settings=bdu mailchimp_sync_announcement --list ${BDU_PORTAL_MAILCHIMP_USER_LIST_ID} --key ${BDU_PORTAL_MAILCHIMP_API_KEY}"
```

https://github.com/edx/edx-platform/blob/open-release/juniper.master/lms/djangoapps/mailing/management/commands/mailchimp_sync_announcements.py#L23-L29

2021-06-02 16:45 UTC, michaellzc approved these changes

2021-06-02 16:45 UTC, michaellzc commented on docker/build/edxapp/docker-run.sh
> +      #eval "${edxpython} ${manage} ${service} --settings=bdu mailchimp_sync_announcements --list ${BDU_PORTAL_MAILCHIMP_USER_LIST_ID}  --key ${BDU_PORTAL_MAILCHIMP_API_KEY}"
```suggestion
```

2021-06-02 16:45 UTC, michaellzc commented on docker/build/edxapp/sync_users_mailchimp.py
> +
```suggestion
```

2021-06-02 16:55 UTC, michaellzc approved these changes

2021-06-02 16:55 UTC, merged